package com.example.bssapp;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bssapp.db.models.ProfessorItem;
import com.example.bssapp.db.models.StudentItem;

import com.example.bssapp.ProfessorItemDao;
import com.example.bssapp.StudentItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig professorItemDaoConfig;
    private final DaoConfig studentItemDaoConfig;

    private final ProfessorItemDao professorItemDao;
    private final StudentItemDao studentItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        professorItemDaoConfig = daoConfigMap.get(ProfessorItemDao.class).clone();
        professorItemDaoConfig.initIdentityScope(type);

        studentItemDaoConfig = daoConfigMap.get(StudentItemDao.class).clone();
        studentItemDaoConfig.initIdentityScope(type);

        professorItemDao = new ProfessorItemDao(professorItemDaoConfig, this);
        studentItemDao = new StudentItemDao(studentItemDaoConfig, this);

        registerDao(ProfessorItem.class, professorItemDao);
        registerDao(StudentItem.class, studentItemDao);
    }
    
    public void clear() {
        professorItemDaoConfig.clearIdentityScope();
        studentItemDaoConfig.clearIdentityScope();
    }

    public ProfessorItemDao getProfessorItemDao() {
        return professorItemDao;
    }

    public StudentItemDao getStudentItemDao() {
        return studentItemDao;
    }

}
