package com.example.bssapp;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bssapp.db.models.ClassItem;
import com.example.bssapp.db.models.ClassProfessorItem;
import com.example.bssapp.db.models.ClassStudentItem;
import com.example.bssapp.db.models.ProfessorItem;
import com.example.bssapp.db.models.SportItem;
import com.example.bssapp.db.models.SpotItem;
import com.example.bssapp.db.models.StudentItem;

import com.example.bssapp.ClassItemDao;
import com.example.bssapp.ClassProfessorItemDao;
import com.example.bssapp.ClassStudentItemDao;
import com.example.bssapp.ProfessorItemDao;
import com.example.bssapp.SportItemDao;
import com.example.bssapp.SpotItemDao;
import com.example.bssapp.StudentItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classItemDaoConfig;
    private final DaoConfig classProfessorItemDaoConfig;
    private final DaoConfig classStudentItemDaoConfig;
    private final DaoConfig professorItemDaoConfig;
    private final DaoConfig sportItemDaoConfig;
    private final DaoConfig spotItemDaoConfig;
    private final DaoConfig studentItemDaoConfig;

    private final ClassItemDao classItemDao;
    private final ClassProfessorItemDao classProfessorItemDao;
    private final ClassStudentItemDao classStudentItemDao;
    private final ProfessorItemDao professorItemDao;
    private final SportItemDao sportItemDao;
    private final SpotItemDao spotItemDao;
    private final StudentItemDao studentItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classItemDaoConfig = daoConfigMap.get(ClassItemDao.class).clone();
        classItemDaoConfig.initIdentityScope(type);

        classProfessorItemDaoConfig = daoConfigMap.get(ClassProfessorItemDao.class).clone();
        classProfessorItemDaoConfig.initIdentityScope(type);

        classStudentItemDaoConfig = daoConfigMap.get(ClassStudentItemDao.class).clone();
        classStudentItemDaoConfig.initIdentityScope(type);

        professorItemDaoConfig = daoConfigMap.get(ProfessorItemDao.class).clone();
        professorItemDaoConfig.initIdentityScope(type);

        sportItemDaoConfig = daoConfigMap.get(SportItemDao.class).clone();
        sportItemDaoConfig.initIdentityScope(type);

        spotItemDaoConfig = daoConfigMap.get(SpotItemDao.class).clone();
        spotItemDaoConfig.initIdentityScope(type);

        studentItemDaoConfig = daoConfigMap.get(StudentItemDao.class).clone();
        studentItemDaoConfig.initIdentityScope(type);

        classItemDao = new ClassItemDao(classItemDaoConfig, this);
        classProfessorItemDao = new ClassProfessorItemDao(classProfessorItemDaoConfig, this);
        classStudentItemDao = new ClassStudentItemDao(classStudentItemDaoConfig, this);
        professorItemDao = new ProfessorItemDao(professorItemDaoConfig, this);
        sportItemDao = new SportItemDao(sportItemDaoConfig, this);
        spotItemDao = new SpotItemDao(spotItemDaoConfig, this);
        studentItemDao = new StudentItemDao(studentItemDaoConfig, this);

        registerDao(ClassItem.class, classItemDao);
        registerDao(ClassProfessorItem.class, classProfessorItemDao);
        registerDao(ClassStudentItem.class, classStudentItemDao);
        registerDao(ProfessorItem.class, professorItemDao);
        registerDao(SportItem.class, sportItemDao);
        registerDao(SpotItem.class, spotItemDao);
        registerDao(StudentItem.class, studentItemDao);
    }
    
    public void clear() {
        classItemDaoConfig.clearIdentityScope();
        classProfessorItemDaoConfig.clearIdentityScope();
        classStudentItemDaoConfig.clearIdentityScope();
        professorItemDaoConfig.clearIdentityScope();
        sportItemDaoConfig.clearIdentityScope();
        spotItemDaoConfig.clearIdentityScope();
        studentItemDaoConfig.clearIdentityScope();
    }

    public ClassItemDao getClassItemDao() {
        return classItemDao;
    }

    public ClassProfessorItemDao getClassProfessorItemDao() {
        return classProfessorItemDao;
    }

    public ClassStudentItemDao getClassStudentItemDao() {
        return classStudentItemDao;
    }

    public ProfessorItemDao getProfessorItemDao() {
        return professorItemDao;
    }

    public SportItemDao getSportItemDao() {
        return sportItemDao;
    }

    public SpotItemDao getSpotItemDao() {
        return spotItemDao;
    }

    public StudentItemDao getStudentItemDao() {
        return studentItemDao;
    }

}
