package com.example.bssapp;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.bssapp.db.models.SpotItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "spot_items".
*/
public class SpotItemDao extends AbstractDao<SpotItem, Long> {

    public static final String TABLENAME = "spot_items";

    /**
     * Properties of entity SpotItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SpotId = new Property(0, Long.class, "spotId", true, "_id");
        public final static Property SpotName = new Property(1, String.class, "spotName", false, "SPOT_NAME");
        public final static Property CreateDate = new Property(2, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property Deleted = new Property(3, boolean.class, "deleted", false, "DELETED");
    }


    public SpotItemDao(DaoConfig config) {
        super(config);
    }
    
    public SpotItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"spot_items\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: spotId
                "\"SPOT_NAME\" TEXT," + // 1: spotName
                "\"CREATE_DATE\" INTEGER," + // 2: createDate
                "\"DELETED\" INTEGER NOT NULL );"); // 3: deleted
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"spot_items\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SpotItem entity) {
        stmt.clearBindings();
 
        Long spotId = entity.getSpotId();
        if (spotId != null) {
            stmt.bindLong(1, spotId);
        }
 
        String spotName = entity.getSpotName();
        if (spotName != null) {
            stmt.bindString(2, spotName);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(3, createDate.getTime());
        }
        stmt.bindLong(4, entity.getDeleted() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SpotItem entity) {
        stmt.clearBindings();
 
        Long spotId = entity.getSpotId();
        if (spotId != null) {
            stmt.bindLong(1, spotId);
        }
 
        String spotName = entity.getSpotName();
        if (spotName != null) {
            stmt.bindString(2, spotName);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(3, createDate.getTime());
        }
        stmt.bindLong(4, entity.getDeleted() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SpotItem readEntity(Cursor cursor, int offset) {
        SpotItem entity = new SpotItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // spotId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // spotName
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // createDate
            cursor.getShort(offset + 3) != 0 // deleted
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SpotItem entity, int offset) {
        entity.setSpotId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSpotName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreateDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setDeleted(cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SpotItem entity, long rowId) {
        entity.setSpotId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SpotItem entity) {
        if(entity != null) {
            return entity.getSpotId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SpotItem entity) {
        return entity.getSpotId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
