package com.example.bssapp;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.bssapp.db.models.StudentItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "student_items".
*/
public class StudentItemDao extends AbstractDao<StudentItem, Long> {

    public static final String TABLENAME = "student_items";

    /**
     * Properties of entity StudentItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StudentId = new Property(0, Long.class, "studentId", true, "_id");
        public final static Property FirstName = new Property(1, String.class, "firstName", false, "FIRST_NAME");
        public final static Property LastName = new Property(2, String.class, "lastName", false, "LAST_NAME");
        public final static Property IsAdult = new Property(3, boolean.class, "isAdult", false, "IS_ADULT");
        public final static Property CreateDate = new Property(4, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property Deleted = new Property(5, boolean.class, "deleted", false, "DELETED");
    }


    public StudentItemDao(DaoConfig config) {
        super(config);
    }
    
    public StudentItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"student_items\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: studentId
                "\"FIRST_NAME\" TEXT," + // 1: firstName
                "\"LAST_NAME\" TEXT," + // 2: lastName
                "\"IS_ADULT\" INTEGER NOT NULL ," + // 3: isAdult
                "\"CREATE_DATE\" INTEGER," + // 4: createDate
                "\"DELETED\" INTEGER NOT NULL );"); // 5: deleted
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"student_items\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StudentItem entity) {
        stmt.clearBindings();
 
        Long studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindLong(1, studentId);
        }
 
        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(2, firstName);
        }
 
        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(3, lastName);
        }
        stmt.bindLong(4, entity.getIsAdult() ? 1L: 0L);
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(5, createDate.getTime());
        }
        stmt.bindLong(6, entity.getDeleted() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StudentItem entity) {
        stmt.clearBindings();
 
        Long studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindLong(1, studentId);
        }
 
        String firstName = entity.getFirstName();
        if (firstName != null) {
            stmt.bindString(2, firstName);
        }
 
        String lastName = entity.getLastName();
        if (lastName != null) {
            stmt.bindString(3, lastName);
        }
        stmt.bindLong(4, entity.getIsAdult() ? 1L: 0L);
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(5, createDate.getTime());
        }
        stmt.bindLong(6, entity.getDeleted() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StudentItem readEntity(Cursor cursor, int offset) {
        StudentItem entity = new StudentItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // studentId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // firstName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lastName
            cursor.getShort(offset + 3) != 0, // isAdult
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // createDate
            cursor.getShort(offset + 5) != 0 // deleted
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StudentItem entity, int offset) {
        entity.setStudentId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFirstName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLastName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsAdult(cursor.getShort(offset + 3) != 0);
        entity.setCreateDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setDeleted(cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StudentItem entity, long rowId) {
        entity.setStudentId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StudentItem entity) {
        if(entity != null) {
            return entity.getStudentId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StudentItem entity) {
        return entity.getStudentId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
